number = input('input: ')
print(type(number))
print('Is Alpha Numeric? {}'.format(number.isalnum()))
print('Is Alpha? {}'.format(number.isalpha()))
print('Is decimal? {}'.format(number.isdecimal()))
print('Is digit? {}'.format(number.isdigit()))
print('Is identigier? {}'.format(number.isidentifier()))
print('Is lower? {}'.format(number.islower()))
print('Is numeric? {}'.format(number.isnumeric()))
print('Is printable? {}'.format(number.isprintable()))
print('Is space? {}'.format(number.isspace()))
print('Is title? {}'.format(number.istitle()))
print('Is upper? {}'.format(number.isupper()))
